######################################
##                                  ##
## ░█▄█░█▀█░█▀█░▀█▀░▀█▀░█▀█░█▀▄░█▀▀ ##
## ░█░█░█░█░█░█░░█░░░█░░█░█░█▀▄░▀▀█ ##
## ░▀░▀░▀▀▀░▀░▀░▀▀▀░░▀░░▀▀▀░▀░▀░▀▀▀ ##
##                                  ##
######################################

# See https://wiki.hypr.land/Configuring/Monitors/

monitor=,1920x1080@60,auto,auto