######################################
##                                  ##
## ░█▀█░█▀▄░█▀█░█▀▀░█▀▄░█▀█░█▄█░█▀▀ ##
## ░█▀▀░█▀▄░█░█░█░█░█▀▄░█▀█░█░█░▀▀█ ##
## ░▀░░░▀░▀░▀▀▀░▀▀▀░▀░▀░▀░▀░▀░▀░▀▀▀ ##
##                                  ##
######################################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$fileManager = yazi
$menu = rofi -show drun
$browser = firefox